# Generated by Django 4.2 on 2026-01-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_name', models.CharField(max_length=100)),
                ('artists', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('total_tickets', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='concerts/')),
            ],
        ),
    ]
