# Generated by Django 4.2 on 2026-01-15 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_userprofile_email_alter_userprofile_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
