# Generated by Django 4.2 on 2026-01-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='show',
            new_name='show_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='user_id',
        ),
    ]
