# Generated by Django 4.2 on 2026-01-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_show_booking_show_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='show_id',
            new_name='show',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
